### ISSUE TITLE
Not working with 5.2

### ISSUE THREAD

**Issue by wrighting** [wrighting/alfresco-cas#3]
The ACE-5661 branch should work (with 201701-GA) but only the share amp

This requires replacing the web.xml file instead of using a web-fragment.xml so I'd prefer to try and stick with using web-fragment if possible

**Comment by wrighting** [comment]
There is a bug - https://issues.alfresco.com/jira/browse/MNT-17858 (don't have access to see this)

In org.alfresco.web.site.servlet.SSOAuthenticationFilter.challengeOrPassThrough the call to "/touch" (wcs/touch) is returning a status of UNAUTHORIZED despite the value of userId being set correctly.
This is because in org.springframework.extensions.webscripts.connector.AlfrescoConnector.applyRequestAuthentication although the credentials are not null, and there is a connector session the session parameter AlfrescoAuthenticator.CS_PARAM_ALF_TICKET is null and therefore the call is made unauthenticated

**Comment by mikelasla** [comment]
I can confirm that ACE-5661 branch approach works for me. Tested Share SSO and SLO on 201707GA

**Comment by coder-zhw** [comment]
We use httpd mod_auth_cas and mod_jk to configure the cas sso in alfresco success, but after login in share , We can't find the logout page, is there any configure in alfresco share?

**Comment by wrighting** [comment]
Not really relevant to this issue but a lot of the share amp is to do with logout

Basically you need to configure your own logout menu items

Also see the [wiki](https://github.com/wrighting/alfresco-cas/wiki/User-Menus)
